name: Terraform Deploy
####
on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1.6.1
        with:
          client-id: ${{ secrets.DEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}

      - name: Set Terraform OIDC vars
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.DEV_AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.DEV_AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.DEV_AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Deploy Infra
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="environment=dev"

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group gocloud-dev-rg \
            --name gocloud-dev-aks \
            --overwrite-existing